Repository conveyal/analysis-ui, pull requests merged in 2019-12, with the labels that each got.

#940 Add AUTH_DISABLED config option
  lib/auth.js
  next.config.js
  now.json
  now.production.json
Labels: feature

#946 Set spellcheck='false' to disable squiggly lines
  lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
  lib/components/analysis/advanced-settings.js
Labels: bug

#950 Refactoring opportunity dataset docs for clarity
  docs/prepare-inputs/upload-opportunity-data.md
Labels: cleanup

#943 Cleaning up OSM command line examples
  docs/prepare-inputs/index.md
Labels: cleanup

#952 Stub out cypress and write sample test
  .eslintrc.json
  .github/workflows/nodejs.yml
  .gitignore
  cypress.env.json.tmp
  cypress.json
  cypress/fixtures/profile.json
  cypress/integration/basic_spec.js
  cypress/integration/login.js
  cypress/integration/status-page.js
  cypress/plugins/index.js
  cypress/screenshots/.gitignore
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/.gitignore
  package.json
  yarn.lock
Labels: feature
