Repository conveyal/analysis-ui, pull requests merged in 2020-08, with the labels that each got.

#1158 Add a "Create Regional Analysis" modal
  cypress/integration/local/analysis.js
  lib/actions/analysis/profile-request.js
  lib/actions/analysis/regional.js
  lib/components/analysis/__tests__/__snapshots__/profile-request-display.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/create-regional.tsx
  lib/components/analysis/profile-request-display.tsx
  lib/components/analysis/regional-results.tsx
  lib/components/analysis/regional.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/map/index.tsx
  lib/components/modification/list.tsx
  lib/components/modifications-map/display-all.js
  lib/components/select.tsx
  lib/leaflet.js
  lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
  lib/modules/r5-version/constants.js
  lib/reducers/__tests__/__snapshots__/analysis.js.snap
  lib/selectors/bundles.js
  lib/selectors/max-trip-duration-minutes.js
  lib/selectors/nearest-percentile-index.js
  lib/selectors/travel-time-percentile.js
  lib/utils/get.js
  lib/utils/local-storage.ts
  package.json
  yarn.lock
Labels: automerge, feature

#1160 August Changelog
  lib/actions/analysis/profile-request.js
  lib/actions/analysis/regional.js
  lib/components/__tests__/__snapshots__/select-project.js.snap
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/aggregate-accessibility.tsx
  lib/components/analysis/create-regional.tsx
  lib/components/analysis/profile-request-display.tsx
  lib/components/analysis/regional-results.tsx
  lib/components/analysis/regional.tsx
  lib/components/list-group-item.tsx
  lib/components/map/index.tsx
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/list.tsx
  lib/components/running-analysis.js
  lib/components/select-region.js
  lib/components/select-region.tsx
  lib/constants/index.js
  lib/hooks/use-route-to.ts
  lib/reducers/__tests__/__snapshots__/analysis.js.snap
  lib/reducers/regional-analyses.js
  lib/with-auth.js
  pages/changelog/20200803.mdx
  pages/changelog/index.js
  pages/regions/[regionId]/regional/index.js
  public/img/changelog/20200803/create.jpg
  public/img/changelog/20200803/regional-comparison.jpg
Labels: automerge, doc

#1162 Changelog update
  pages/changelog/20200803.mdx
Labels: automerge

#1163 Fix a bug when selecting a single opportunity dataset for a regional …
  lib/components/analysis/create-regional.tsx
Labels: automerge, bug

#1167 Correct description of R5 bug
  pages/changelog/20200803.mdx
Labels: automerge

#1166 Persist selected projectId across pages
  cypress/integration/local/analysis.js
  cypress/support/commands.js
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/analysis/create-regional.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/edit-bundle.tsx
  lib/components/project-title.tsx
  lib/components/sidebar.tsx
  public/img/changelog/20200803/create.jpg
  public/img/changelog/20200803/regional-comparison.jpg
Labels: automerge, bug

#1155 Building out Cypress tests
  cypress.json
  cypress/fixtures/regions/nky/TANK-GTFS.zip
  cypress/fixtures/regions/nky/null-GTFS.zip
  cypress/fixtures/regions/scratch.json
  cypress/integration/local/analysis.js
  cypress/integration/local/bundles.js
  cypress/integration/local/modifications.js
  cypress/integration/local/regions.js
  cypress/snapshots/local/all.js/.gitignore
  cypress/snapshots/local/all.js/chart-no-variation.snap.png
  cypress/snapshots/local/all.js/chart-with-comparison.snap.png
  cypress/snapshots/local/all.js/direct-bike-access-chart.snap.png
  cypress/snapshots/local/all.js/single-scenario-chart.snap.png
  cypress/support/commands.js
Labels: WIP, automerge

#1169 Hide incomplete analyses from comparison
  lib/components/analysis/create-regional.tsx
  lib/selectors/comparison-analyses.js
Labels: automerge, bug

#1171 Fix no opportunity dataset error
  lib/actions/analysis/regional.js
  lib/components/analysis/create-regional.tsx
  lib/components/analysis/index.tsx
  lib/components/analysis/regional-results.tsx
  lib/components/analysis/regional.tsx
  lib/selectors/regional-comparison-cutoff.js
  lib/selectors/regional-comparison-percentile.js
  lib/selectors/regional-display-cutoff.js
  lib/selectors/regional-display-percentile.js
Labels: automerge, bug

#1172 Remove cross browser tests
  .github/workflows/cross-browser.yml
Labels: automerge

#1188 Add regional analysis name to legend
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/regional-results.tsx
Labels: automerge, feature

#1187 Add detail about reroute modifications to user manual
  docs/edit-scenario/modifications.md
Labels: automerge

#1186 Remove react-datetime
  lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
  lib/components/analysis/profile-request-editor.tsx
  package.json
  pages/_app.tsx
  yarn.lock
Labels: automerge, cleanup, dependencies

#1191 Don't import within integration tests
  cypress/integration/local/opportunities.js
  cypress/support/index.js
Labels: automerge

#1170 Expanding Cypress tests
  cypress.json
  cypress/fixtures/regions/scratch.json
  cypress/integration/local/analysis.js
  cypress/integration/local/modifications.js
  cypress/snapshots/local/all.js/regional-comparison-legend.snap.png
  cypress/snapshots/local/all.js/regional-single-legend.snap.png
  cypress/snapshots/local/analysis.js/regional-comparison-legend.snap.png
  cypress/snapshots/local/analysis.js/regional-single-legend.snap.png
  cypress/support/commands.js
Labels: automerge

#1200 (Deploy to production) Handle viewing a regional analysis with deleted bundle or project
  lib/components/analysis/profile-request-display.tsx
Labels: automerge, bug

#1193 Minor Cypress tests refactor
  .github/workflows/lint-jest-build.yml
  cypress/.gitignore
  cypress/integration/0-regions.js
  cypress/integration/1-bundles.js
  cypress/integration/2-opportunities.js
  cypress/integration/3-projects.js
  cypress/integration/4-scenarios.js
  cypress/integration/5-modifications.js
  cypress/integration/6-analysis.js
  cypress/integration/basic.js
  cypress/integration/local/all.js
  cypress/integration/login.js
  cypress/integration/region.js
  cypress/integration/status-page.js
  cypress/plugins/index.js
  cypress/snapshots/local/all.js/.gitignore
  cypress/snapshots/local/all.js/chart-no-variation.snap.png
  cypress/snapshots/local/all.js/chart-with-comparison.snap.png
  cypress/snapshots/local/all.js/direct-bike-access-chart.snap.png
  cypress/snapshots/local/all.js/regional-comparison-legend.snap.png
  cypress/snapshots/local/all.js/regional-single-legend.snap.png
  cypress/snapshots/local/all.js/single-scenario-chart.snap.png
  cypress/snapshots/local/analysis.js/.gitignore
  cypress/snapshots/local/analysis.js/chart-no-variation.snap.png
  cypress/snapshots/local/analysis.js/chart-with-comparison.snap.png
  cypress/snapshots/local/analysis.js/direct-bike-access-chart.snap.png
  cypress/snapshots/local/analysis.js/regional-comparison-legend.snap.png
  cypress/snapshots/local/analysis.js/regional-single-legend.snap.png
  cypress/snapshots/local/analysis.js/single-scenario-chart.snap.png
  cypress/support/commands.js
Labels: automerge

#1181 Update dependabot.yml
  .github/.kodiak.toml
  .github/dependabot.yml
  docs/edit-scenario/modifications.md
Labels: automerge, cleanup, dependencies

#1201 Add stale issue bot
  .github/stale.yml
Labels: automerge, cleanup

#1202 One-line user manual addition: modify streets polygons cannot overlap
  docs/edit-scenario/modifications.md
Labels: automerge

#1190 Hide auto-create stops until route is drawn
  cypress/integration/5-modifications.js
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/add-trip-pattern.tsx
  lib/components/modification/edit-alignment.tsx
Labels: automerge, bug

#1183 Don't show invalid travel time distributions
  .babelrc
  cypress/integration/2-opportunities.js
  jest/enzyme.js
  lib/actions/analysis/index.js
  lib/actions/analysis/parse-times-data.ts
  lib/components/analysis/__tests__/__snapshots__/map.js.snap
  lib/components/analysis/__tests__/map.js
  lib/components/analysis/boxplot.tsx
  lib/components/analysis/index.tsx
  lib/components/analysis/map.js
  lib/components/analysis/map.tsx
  lib/components/analysis/minute-ticks.tsx
  lib/components/map/destination-travel-time-distribution.tsx
  lib/selectors/comparison-destination-travel-time-distribution.js
  lib/selectors/destination-travel-time-distribution.js
  lib/selectors/index.js
  next.config.js
  package.json
  yarn.lock
Labels: automerge, bug

#1184 Ensure from and to time in order
  cypress.json
  cypress/integration/1-bundles.js
  cypress/integration/2-opportunities.js
  cypress/integration/3-projects.js
  cypress/integration/6-analysis.js
  cypress/snapshots/6-analysis.js/chart-no-variation.snap.png
  cypress/snapshots/6-analysis.js/chart-with-comparison.snap.png
  cypress/snapshots/6-analysis.js/direct-bike-access-chart.snap.png
  cypress/snapshots/6-analysis.js/single-scenario-chart.snap.png
  cypress/support/commands.js
  lib/components/analysis/mode-selector.tsx
  lib/components/analysis/profile-request-editor.tsx
  lib/components/analysis/results-sliders.tsx
  lib/components/create-project.js
  lib/components/report/__tests__/adjust-dwell-time.js
  lib/components/report/__tests__/adjust-frequency.js
  lib/components/report/__tests__/adjust-speed.js
  lib/components/report/__tests__/modification.js
  lib/components/report/__tests__/remove-stops.js
  lib/components/report/__tests__/remove-trips.js
  lib/components/report/__tests__/reroute.js
  lib/utils/mock-data.js
  package.json
  yarn.lock
Labels: automerge, bug
