Repository conveyal/analysis-ui, pull requests merged in 2020-06, with the labels that each got.

#1092 Latest round of Cypress tests
  cypress.json
  cypress/fixtures/regions/nky/people.grid
  cypress/fixtures/regions/scratch.json
  cypress/integration/local/all.js
  cypress/integration/local/analysis.js
  cypress/integration/local/bundles.js
  cypress/integration/local/modifications.js
  cypress/integration/local/opportunities.js
  cypress/integration/local/projects.js
  cypress/integration/local/regions.js
  cypress/integration/local/scenarios.js
  cypress/support/commands.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: cleanup

#1099 Fix network bundle name editing
  lib/components/confirm-button.tsx
  lib/components/edit-bundle.tsx
  lib/reducers/__tests__/__snapshots__/analysis.js.snap
Labels: automerge, bug

#1100 Additional logic for analysis panel
  lib/components/analysis/mode-selector.tsx
  lib/components/analysis/profile-request-editor.tsx
Labels: automerge, feature, optimization

#1103 June release fixes
  lib/actions/analysis/index.js
  lib/actions/region.js
  lib/components/__tests__/__snapshots__/edit-project.js.snap
  lib/components/__tests__/__snapshots__/import-modifications.js.snap
  lib/components/__tests__/__snapshots__/import-shapefile.js.snap
  lib/components/__tests__/__snapshots__/project-title.js.snap
  lib/components/__tests__/__snapshots__/select-project.js.snap
  lib/components/analysis/__tests__/__snapshots__/title.js.snap
  lib/components/analysis/bookmark-chooser.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/analysis/title.tsx
  lib/components/create-project.js
  lib/components/edit-project.js
  lib/components/import-modifications.js
  lib/components/import-shapefile.js
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/list.js
  lib/components/project-title.js
  lib/components/select-project.js
  lib/components/select-resource.js
  lib/constants/index.js
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/heading.js.snap
  lib/modules/opportunity-datasets/components/heading.js
  lib/reducers/analysis.js
  lib/selectors/comparison-in-progress.js
  lib/selectors/comparison-project.js
  lib/selectors/current-project-id.js
  lib/selectors/displayed-comparison-project.js
  lib/selectors/displayed-comparison-scenario-name.js
  lib/selectors/displayed-project.js
  lib/selectors/displayed-scenario-name.js
  lib/selectors/profile-request-has-changed.js
  lib/selectors/profile-request-lonlat.js
  pages/index.js
  pages/regions/[regionId]/regional/index.js
  pages/regions/[regionId]/resources/upload.js
Labels: automerge, bug, cleanup

#1102 Cypress modifications refactor and general speed up
  cypress/integration/local/modifications.js
  cypress/integration/local/opportunities.js
  cypress/support/commands.js
  cypress/support/index.js
  lib/constants/index.js
  pages/_document.js
  pages/_document.tsx
  public/img/conveyal-128x128.png
Labels: automerge, cleanup

#1105 Create modification modal
  cypress/integration/local/modifications.js
  lib/chakra.js
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/__tests__/__snapshots__/import-modifications.js.snap
  lib/components/analysis/__tests__/__snapshots__/bookmark-chooser.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/single-point-settings.tsx
  lib/components/modification/__tests__/__snapshots__/adjust-speed.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/__tests__/__snapshots__/select-feed-and-routes.js.snap
  lib/components/modification/__tests__/__snapshots__/select-feed-route-and-patterns.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/create.js
  lib/components/modification/create.tsx
  lib/components/modification/list.js
  lib/components/modification/street-form.tsx
  lib/components/select.tsx
  lib/hooks/use-controlled-input.ts
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/selector.js.snap
Labels: automerge, feature

#1107 June Release Fixes (2)
  cypress/integration/local/analysis.js
  cypress/integration/local/modifications.js
  lib/components/__tests__/__snapshots__/collapsible.js.snap
  lib/components/__tests__/collapsible.js
  lib/components/analysis/__tests__/__snapshots__/scenario-application-error.js.snap
  lib/components/analysis/__tests__/__snapshots__/title.js.snap
  lib/components/analysis/__tests__/scenario-application-error.js
  lib/components/analysis/index.tsx
  lib/components/analysis/profile-request-editor.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/analysis/title.tsx
  lib/components/collapsible.js
  lib/components/minutes-seconds.js
  lib/components/minutes-seconds.tsx
  lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/components/modification/__tests__/__snapshots__/edit-alignment.js.snap
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/__tests__/__snapshots__/variants.js.snap
  lib/components/modification/add-trip-pattern.js
  lib/components/modification/create.tsx
  lib/components/modification/edit-alignment.tsx
  lib/components/modification/phase.js
  lib/components/modification/segment-speeds.js
  lib/components/modification/segment-speeds.tsx
  lib/components/modification/timetable-entry.js
  lib/components/modification/timetable.js
  lib/components/modification/timetable.tsx
  lib/components/modification/timetables.js
  lib/components/modification/variants.js
  lib/components/number-input.tsx
  lib/components/panel.js
  lib/components/speed.tsx
  lib/components/time-picker.js
  lib/components/transit-mode-selector.js
  lib/containers/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/containers/__tests__/add-trip-pattern.js
  lib/hooks/use-controlled-input.ts
  lib/selectors/profile-request-lonlat.js
  next.config.js
Labels: automerge, bug

#1109 Modify controlled input hook to prevent resetting cursors in inputs
  cypress/integration/local/modifications.js
  lib/components/__tests__/__snapshots__/panel.js.snap
  lib/components/__tests__/__snapshots__/variant-editor.js.snap
  lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/profile-request-editor.tsx
  lib/components/analysis/regional-results.js
  lib/components/analysis/regional.js
  lib/components/analysis/results-sliders.tsx
  lib/components/controlled-select.tsx
  lib/components/minutes-seconds.tsx
  lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/add-trip-pattern.js
  lib/components/modification/phase.js
  lib/components/modification/street-form.tsx
  lib/components/modification/timetable-entry.js
  lib/components/modification/timetable-entry.tsx
  lib/components/panel.js
  lib/components/sidebar.js
  lib/components/time-picker.tsx
  lib/containers/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/hooks/use-controlled-input.ts
  lib/with-auth.js
  styles.css
Labels: automerge, bug, optimization

#1106 June Changelog
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/select-region.js
  pages/changelog/202006.mdx
  pages/changelog/index.js
  public/img/changelog/202006/comparison.jpg
  public/img/changelog/202006/ltscomparison.jpg
Labels: automerge, feature

#1110 June release fixes (3)
  lib/components/analysis/regional.js
  lib/components/analysis/single-point-settings.tsx
  lib/components/minutes-seconds.tsx
  lib/components/time-picker.tsx
  lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
  lib/modules/r5-version/constants.js
  lib/reducers/__tests__/__snapshots__/analysis.js.snap
  lib/reducers/__tests__/analysis.js
  lib/reducers/analysis.js
  lib/utils/time.js
  next.config.js
  package.json
  yarn.lock
Labels: automerge, bug

#1108 Street network modifications docs
  docs/edit-scenario/index.md
  docs/edit-scenario/modifications.md
  docs/static/img/add-street.png
  docs/static/img/create-mod-dialog.png
  docs/static/img/draw-a-polygon.png
  docs/static/img/street-mod-settings.png
Labels: automerge, doc

#1112 Bookmark fixes
  lib/actions/analysis/index.js
  lib/actions/bookmark.ts
  lib/components/analysis/__tests__/bookmark-chooser.js
  lib/components/analysis/bookmark-chooser.tsx
  lib/components/analysis/mode-selector.tsx
Labels: automerge, bug

#1114 v4.9.0 to v5.9.0
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/modification/street-form.tsx
  lib/components/select-region.js
  lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
  lib/modules/r5-version/constants.js
  lib/reducers/__tests__/__snapshots__/analysis.js.snap
  pages/changelog/202006.mdx
  pages/changelog/index.js
Labels: automerge

#1119 Run Analysis Backend for automating Cypress Tests
  .github/workflows/cross-browser.yml
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/lint-jest-build.yml
  .github/workflows/lint_jest_build.yml
  analysis.properties
  cypress/integration/local/opportunities.js
  cypress/integration/local/regions.js
  cypress/support/commands.js
  lib/components/sidebar.tsx
  lib/hooks/use-route-changing.ts
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
  lib/modules/opportunity-datasets/components/list.js
  package.json
  yarn.lock
Labels: automerge, feature, optimization

#1117 Use NEXT_PUBLIC_ for client side environment vars
  .env
  .github/workflows/cross-browser.yml
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/lint-jest-build.yml
  .github/workflows/lint_jest_build.yml
  .gitignore
  analysis.properties
  cypress.env.json.tmp
  cypress/integration/local/opportunities.js
  cypress/integration/local/regions.js
  cypress/support/commands.js
  jest.config.js
  lib/components/map/index.js
  lib/components/map/mapbox-gl.js
  lib/components/sidebar.tsx
  lib/constants/index.js
  lib/hooks/use-route-changing.ts
  lib/leaflet.js
  lib/logrocket.js
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
  lib/modules/opportunity-datasets/components/list.js
  lib/user.js
  lib/utils/get-route-polyline.js
  lib/utils/mapbox-search.js
  lib/with-auth.js
  next.config.js
  package.json
  pages/_app.tsx
  pages/status.js
  yarn.lock
Labels: automerge, cleanup

#1116 Update documentation screenshots
  docs/analysis/configuration.md
  docs/analysis/index.md
  docs/analysis/regional.md
  docs/edit-scenario/usage.md
  docs/static/img/analysis-comparison.png
  docs/static/img/analysis-default-settings.png
  docs/static/img/analysis-settings.png
  docs/static/img/analysis-stacked-percentile.png
  docs/static/img/analysis-start.png
  docs/static/img/blank-geometry.png
  docs/static/img/create-project.png
  docs/static/img/create-regional-analysis.png
  docs/static/img/destination-travel-time-distribution.png
  docs/static/img/edit-scenario.png
  docs/static/img/export-modifications.PNG
  docs/static/img/frequency-entry.png
  docs/static/img/import-analyst.png
  docs/static/img/modification-error.png
  docs/static/img/new-scenario.png
  docs/static/img/overlapping-isochrones.png
  docs/static/img/ready-for-regional-analysis.png
  docs/static/img/regional-comparison.png
  docs/static/img/sampling-distribution.png
  docs/static/img/scenario-error.png
  docs/static/img/scenario-warning.png
  docs/static/img/seattle-comparison.jpeg
  docs/static/img/seattle-isos.gif
  docs/static/img/select-analysis.png
  docs/static/img/select-import-modifications-from-shapefile.png
  docs/static/img/select-import-modifications.png
  docs/static/img/select-project.png
  docs/static/img/stacked-percentile-comparison.png
  docs/static/img/travel-time-slider.gif
  docs/static/img/trip-drawn.png
  docs/static/img/upload-csv.png
  docs/static/img/variant-editor.png
Labels: automerge, doc

#1123 Add console error and exit if percentile curves do not exist
  lib/components/analysis/stacked-percentile-selector.tsx
  lib/components/analysis/stacked-percentile.tsx
  lib/reducers/__tests__/__snapshots__/network.js.snap
  lib/reducers/__tests__/network.js
Labels: automerge, bug
