Repository conveyal/analysis-ui, pull requests merged in 2020-02, with the labels that each got.

#1007 Extend portland test region bounds to full service area
  cypress/fixtures/regions.json
  cypress/fixtures/regions/portland/overpass-query.txt
Labels: cleanup

#1014 Clarify behaviour of the Adjust Speed modification in the docs
  docs/edit-scenario/modifications.md
  docs/glossary.md
  docs/static/img/segment-selector.png
Labels: cleanup, doc

#1018 Fix bug causing long modification names to change layout
  lib/components/analysis/__tests__/__snapshots__/title.js.snap
  lib/components/analysis/title.js
  lib/components/modification/__tests__/__snapshots__/editor.js.snap
  lib/components/modification/editor.js
  lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
  styles.css
Labels: bug

#1012 Select Regional Analysis Display Cutoffs
  lib/actions/analysis/__tests__/__snapshots__/regional.js.snap
  lib/actions/analysis/regional.js
  lib/actions/fetch-signed-s3-url.js
  lib/actions/index.js
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/__tests__/__snapshots__/import-modifications.js.snap
  lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-analysis-selector.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/__tests__/regional-results.js
  lib/components/analysis/regional-analysis-selector.js
  lib/components/analysis/regional-results-list.js
  lib/components/analysis/regional-results.js
  lib/components/analysis/regional.js
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/select.js
  lib/containers/__tests__/__snapshots__/bookmark-chooser.js.snap
  lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
  lib/containers/regional-analysis-results.js
  lib/hooks/use-controlled-input.js
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/selector.js.snap
  lib/reducers.js
  lib/reducers/__tests__/__snapshots__/region.js.snap
  lib/reducers/regional-analyses.js
  lib/selectors/aggregate-accessibility.js
  lib/selectors/comparison-aggregate-accessibility.js
  lib/selectors/comparison-analyses.js
  lib/selectors/comparison-regional-analysis.js
  lib/selectors/current-regional-analysis-id.js
  lib/selectors/regional-analyses.js
  lib/selectors/regional-comparison-cutoff.js
  lib/selectors/regional-comparison-percentile.js
  lib/selectors/regional-display-cutoff.js
  lib/selectors/regional-display-grid.js
  lib/selectors/regional-display-percentile.js
  lib/selectors/regional-display-scale.js
  lib/selectors/regional-grid.js
  lib/utils/mock-data.js
  pages/_app.js
  pages/regions/[regionId]/regional/index.js
Labels: experimental, feature

#1024 Fix display when viewing non-multicutoff
  lib/selectors/regional-comparison-cutoff.js
  lib/selectors/regional-comparison-percentile.js
  lib/selectors/regional-display-cutoff.js
  lib/selectors/regional-display-percentile.js
Labels: bug

#1025 Update changelog
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/select-region.js
  pages/changelog/201909.mdx
  pages/changelog/201910.mdx
  pages/changelog/20200210.mdx
  pages/changelog/index.js
  public/img/changelog/20200210/after.jpg
  public/img/changelog/20200210/before.jpg
  public/img/changelog/20200210/comparison-after.jpg
  public/img/changelog/20200210/comparison-before.jpg
  public/logo.svg
Labels: feature

#1027 Decrease polling delays
  lib/actions/analysis/index.js
  lib/components/analysis/regional-results-list.js
Labels: optimization

#1028 Update recommended r5 version
  lib/__tests__/__snapshots__/reducers.js.snap
  lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
  lib/modules/r5-version/components/__tests__/__snapshots__/selector.js.snap
  lib/modules/r5-version/constants.js
Labels: feature

#1032 Github Workflows Updates
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/lint_jest_build.yml
  .gitignore
Labels: feature, optimization

#1004 Improvements to the convert to frequency modification docs
  docs/edit-scenario/modifications.md
  docs/static/img/select-trip.png
Labels: cleanup

#1026 Shapefile import docs/tests
  cypress/fixtures/regions/download.sh
  cypress/fixtures/regions/mcpherson/.gitignore
  cypress/fixtures/regions/mcpherson/README.md
  cypress/fixtures/regions/mcpherson/overpass-query.txt
  docs/edit-scenario/usage.md
  docs/prepare-inputs/index.md
Labels: cleanup

#1041 Prevent regional redraw
  lib/components/analysis/regional-results-list.js
  lib/components/analysis/regional.js
  lib/components/map/analysis-bounds.js
  lib/containers/regional-analysis-results.js
  lib/hooks/use-interval.js
  lib/selectors/comparison-regional-analysis-id.js
  lib/selectors/regional-display-grid.js
  lib/selectors/regional-grid.js
  pages/changelog/dev.mdx
  pages/changelog/index.js
  pages/regions/[regionId]/regional/index.js
Labels: bug

#1038 Fix status page server request
  lib/hooks/use-request.js
  pages/admin/index.js
  pages/changelog/index.js
  pages/status.js
Labels: bug

#1031 Disable bundle deletion while bundle is in use
  .github/workflows/integration.yml
  i18n/en.json
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/__tests__/__snapshots__/edit-project.js.snap
  lib/components/__tests__/edit-bundle.js
  lib/components/edit-bundle.js
  lib/components/edit-project.js
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/list.js
  lib/components/modification/list.js
  pages/regions/[regionId]/bundles/[bundleId].js
  pages/regions/[regionId]/bundles/index.js
  pages/regions/[regionId]/projects/[projectId]/edit.js
  pages/regions/[regionId]/projects/[projectId]/index.js
Labels: bug, feature

#1045 Ensure auth is provided to the OD upload page
  pages/regions/[regionId]/opportunities/upload.js
Labels: bug

#1042 Ensure regional analysis can be deleted while running
  lib/actions/analysis/regional.js
  lib/components/analysis/regional.js
  lib/reducers/__tests__/__snapshots__/region.js.snap
  lib/reducers/__tests__/region.js
  lib/reducers/region.js
  lib/reducers/regional-analyses.js
  pages/regions/[regionId]/regional/index.js
Labels: bug

#1047 Merge to master
  .github/workflows/deploy.yml
  .github/workflows/integration.yml
  .github/workflows/lint_jest_build.yml
  .gitignore
  cypress/fixtures/regions/download.sh
  cypress/fixtures/regions/mcpherson/.gitignore
  cypress/fixtures/regions/mcpherson/README.md
  cypress/fixtures/regions/mcpherson/overpass-query.txt
  docs/edit-scenario/modifications.md
  docs/edit-scenario/usage.md
  docs/prepare-inputs/index.md
  docs/static/img/select-trip.png
  i18n/en.json
  lib/actions/analysis/regional.js
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/__tests__/__snapshots__/edit-project.js.snap
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/__tests__/edit-bundle.js
  lib/components/analysis/regional-results-list.js
  lib/components/analysis/regional.js
  lib/components/edit-bundle.js
  lib/components/edit-project.js
  lib/components/map/analysis-bounds.js
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/list.js
  lib/components/modification/list.js
  lib/components/select-region.js
  lib/containers/regional-analysis-results.js
  lib/hooks/use-interval.js
  lib/hooks/use-request.js
  lib/modules/opportunity-datasets/components/status.js
  lib/reducers/__tests__/__snapshots__/region.js.snap
  lib/reducers/__tests__/region.js
  lib/reducers/region.js
  lib/reducers/regional-analyses.js
  lib/selectors/comparison-regional-analysis-id.js
  lib/selectors/regional-display-grid.js
  lib/selectors/regional-grid.js
  pages/admin/index.js
  pages/changelog/20200228.mdx
  pages/changelog/index.js
  pages/regions/[regionId]/bundles/[bundleId].js
  pages/regions/[regionId]/bundles/index.js
  pages/regions/[regionId]/opportunities/upload.js
  pages/regions/[regionId]/projects/[projectId]/edit.js
  pages/regions/[regionId]/projects/[projectId]/index.js
  pages/regions/[regionId]/regional/index.js
  pages/status.js
  styles.css
Labels: bug, feature
