Repository conveyal/analysis-ui, pull requests merged in 2020-07, with the labels that each got.

#1132 Set travel time percentile correctly
  lib/actions/analysis/regional.js
Labels: automerge, bug

#1134 Production Deployment, Select travel time percentile correctly
  lib/actions/analysis/regional.js
Labels: automerge, bug

#1120 Modifications list changes
  .github/workflows/cross-browser.yml
  cypress/integration/local/analysis.js
  cypress/integration/local/bundles.js
  cypress/integration/local/modifications.js
  cypress/integration/local/opportunities.js
  cypress/integration/local/projects.js
  cypress/integration/local/regions.js
  cypress/integration/local/scenarios.js
  cypress/support/commands.js
  i18n/en.json
  lib/actions/project.js
  lib/components/__tests__/__snapshots__/edit-region.js.snap
  lib/components/__tests__/__snapshots__/import-modifications.js.snap
  lib/components/__tests__/__snapshots__/project-title.js.snap
  lib/components/__tests__/__snapshots__/select-project.js.snap
  lib/components/__tests__/__snapshots__/variant-editor.js.snap
  lib/components/__tests__/project-title.js
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/confirm-button.tsx
  lib/components/editable.tsx
  lib/components/export-project.js
  lib/components/export-project.tsx
  lib/components/flex-container.js
  lib/components/icon-button.tsx
  lib/components/list-group-item.tsx
  lib/components/modification/__tests__/__snapshots__/editor.js.snap
  lib/components/modification/__tests__/__snapshots__/json-editor.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/__tests__/__snapshots__/variants.js.snap
  lib/components/modification/__tests__/editor.js
  lib/components/modification/__tests__/json-editor.js
  lib/components/modification/create.tsx
  lib/components/modification/editor.js
  lib/components/modification/editor.tsx
  lib/components/modification/fit-bounds.tsx
  lib/components/modification/json-editor.js
  lib/components/modification/list.js
  lib/components/modification/list.tsx
  lib/components/modification/variants.tsx
  lib/components/project-title.js
  lib/components/project-title.tsx
  lib/components/running-analysis.js
  lib/components/select-project.js
  lib/components/select-project.tsx
  lib/components/sidebar.tsx
  lib/components/variant-editor.js
  lib/components/variant-editor.tsx
  lib/constants/index.js
  lib/containers/__tests__/__snapshots__/modification-editor.js.snap
  lib/containers/__tests__/modification-editor.js
  lib/hooks/use-controlled-input.ts
  lib/hooks/use-route-to.ts
  lib/layouts/map.js
  lib/router.ts
  package.json
  pages/regions/[regionId]/projects/[projectId]/index.tsx
  pages/regions/[regionId]/projects/[projectId]/modifications/index.tsx
  yarn.lock
Labels: UX, automerge, feature

#1121 Building out cypress tests
  cypress/fixtures/regions/scratch-results.json
  cypress/fixtures/regions/scratch.json
  cypress/integration/.eslintrc.json
  cypress/integration/local/analysis.js
  cypress/integration/local/bundles.js
  cypress/integration/local/modifications.js
  cypress/integration/local/opportunities.js
  cypress/integration/local/regions.js
  cypress/plugins/index.js
  cypress/snapshots/local/analysis.js/.gitignore
  cypress/snapshots/local/analysis.js/chart-no-variation.snap.png
  cypress/snapshots/local/analysis.js/chart-with-comparison.snap.png
  cypress/snapshots/local/analysis.js/direct-bike-access-chart.snap.png
  cypress/snapshots/local/analysis.js/single-scenario-chart.snap.png
  cypress/support/commands.js
  lib/actions/analysis/regional.js
  lib/components/analysis/__tests__/__snapshots__/bookmark-chooser.js.snap
  lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
  lib/components/analysis/advanced-settings.tsx
  lib/components/analysis/bookmark-chooser.tsx
  lib/components/analysis/index.tsx
  lib/components/analysis/mode-selector.tsx
  lib/components/analysis/profile-request-editor.tsx
  lib/components/analysis/results-sliders.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/analysis/stacked-percentile-selector.tsx
  lib/components/analysis/stacked-percentile.tsx
  yarn.lock
Labels: automerge

#1140 Add dependabot
  .github/dependabot.yml
  .kodiak.toml
Labels: automerge, dependencies

#1152 Split nextjs build from cypress running
  .github/workflows/lint-jest-build.yml
  cypress.json
Labels: automerge, cleanup, optimization

#1143 Update User Manual
  docs/analysis/methodology.md
  docs/edit-scenario/modifications.md
  docs/learn-more/lts.md
  docs/learn-more/osm.md
  docs/learn-more/pnr.md
Labels: automerge, doc

#1135 allow basemap style to be set with NEXT_PUBLIC_MAPBOX_STYLE
  .env
  lib/components/map/mapbox-gl.js
  lib/leaflet.js
Labels: automerge, feature

#1156 Add the ability to select destination grids
  __mocks__/react-leaflet-control.js
  cypress/integration/local/analysis.js
  i18n/en.json
  lib/actions/analysis/__tests__/__snapshots__/regional.js.snap
  lib/actions/analysis/regional.js
  lib/components/__tests__/__snapshots__/edit-project.js.snap
  lib/components/__tests__/__snapshots__/edit-region.js.snap
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
  lib/components/analysis/__tests__/__snapshots__/legend.js.snap
  lib/components/analysis/__tests__/__snapshots__/profile-request-display.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/__tests__/profile-request-display.js
  lib/components/analysis/__tests__/regional-results.js
  lib/components/analysis/aggregate-accessibility.tsx
  lib/components/analysis/aggregation-area.js
  lib/components/analysis/aggregation-area.tsx
  lib/components/analysis/legend.js
  lib/components/analysis/legend.tsx
  lib/components/analysis/mode-summary.tsx
  lib/components/analysis/profile-request-display.js
  lib/components/analysis/profile-request-display.tsx
  lib/components/analysis/regional-results.js
  lib/components/analysis/regional-results.tsx
  lib/components/analysis/regional.js
  lib/components/analysis/regional.tsx
  lib/components/link.js
  lib/constants/index.js
  lib/modules/opportunity-datasets/components/selector.js
  lib/selectors/regional-comparison-destination-pointset.ts
  lib/selectors/regional-display-destination-pointset.ts
  lib/selectors/regional-grid.js
  lib/utils/mock-data.js
  lib/with-redux.js
  package.json
  pages/regions/[regionId]/regional/index.js
  yarn.lock
Labels: UX, automerge
