Repository conveyal/analysis-ui, pull requests merged in 2020-05, with the labels that each got.

#1096 Grid documentation + fixing broken formatting
  .prettierignore
  docs/analysis/configuration.md
  docs/analysis/index.md
  docs/edit-scenario/index.md
  docs/edit-scenario/modifications.md
  docs/edit-scenario/usage.md
  docs/glossary.md
  docs/glossary.rst
  docs/prepare-inputs/upload-opportunity-data.md
Labels: cleanup

#1093 WebVitals Tracking
  lib/logrocket.js
  lib/utils/log-error.js
  package.json
  pages/_app.js
  pages/_app.tsx
  yarn.lock
Labels: feature, optimization

#1094 Add bike traffic stress selector
  lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
  lib/components/analysis/__tests__/advanced-settings.js
  lib/components/analysis/advanced-settings.js
  lib/components/analysis/index.js
  lib/containers/__tests__/__snapshots__/single-point-analysis.js.snap
Labels: feature
