Repository conveyal/analysis-ui, pull requests merged in 2020-01, with the labels that each got.

#958 Scenario names in modifications
  i18n/en.json
  lib/components/__tests__/__snapshots__/create-region.js.snap
  lib/components/__tests__/__snapshots__/edit-bundle.js.snap
  lib/components/__tests__/__snapshots__/edit-project.js.snap
  lib/components/__tests__/__snapshots__/edit-region.js.snap
  lib/components/__tests__/__snapshots__/import-modifications.js.snap
  lib/components/__tests__/__snapshots__/import-shapefile.js.snap
  lib/components/__tests__/__snapshots__/project-title.js.snap
  lib/components/__tests__/__snapshots__/select-project.js.snap
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/__tests__/__snapshots__/variant-editor.js.snap
  lib/components/analysis/__tests__/__snapshots__/advanced-settings.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-analysis-selector.js.snap
  lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/components/modification/__tests__/__snapshots__/json-editor.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/__tests__/__snapshots__/variants.js.snap
  lib/components/modification/__tests__/variants.js
  lib/components/modification/variants.js
  lib/components/modifications-map/__tests__/__snapshots__/add-trip-pattern-layer.js.snap
  lib/components/modifications-map/__tests__/__snapshots__/hop-select-polygon.js.snap
  lib/components/modifications-map/__tests__/__snapshots__/stop-select-polygon.js.snap
  lib/containers/__tests__/__snapshots__/modification-editor.js.snap
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/list.js.snap
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/upload.js.snap
  lib/modules/opportunity-datasets/components/__tests__/dotmap.js
  lib/utils/component.js
  package.json
  yarn.lock
Labels: feature

#974 Fix spinner that was no longer being displayed
  lib/with-initial-fetch.js
Labels: bug

#945 New admin page
  docs/prepare-inputs/index.md
  docs/prepare-inputs/upload-opportunity-data.md
  lib/__tests__/__snapshots__/reducers.js.snap
  lib/auth.js
  lib/components/__tests__/__snapshots__/create-region.js.snap
  lib/components/__tests__/__snapshots__/edit-region.js.snap
  lib/components/admin-job-dashboard.js
  lib/components/admin-worker-list.js
  lib/components/admin-worker.js
  lib/components/create-region.js
  lib/components/text-link.js
  lib/get-initial-auth.js
  lib/modules/admin/actions.js
  lib/modules/admin/components/index.js
  lib/modules/admin/components/job-dashboard.js
  lib/modules/admin/components/main-dashboard.js
  lib/modules/admin/components/sparkline.js
  lib/modules/admin/components/worker-dashboard.js
  lib/modules/admin/constants.js
  lib/modules/admin/index.js
  lib/modules/admin/reducer.js
  lib/modules/admin/selectors.js
  lib/modules/admin/types.js
  lib/modules/admin/utils.js
  lib/reducers.js
  lib/use-request.js
  lib/with-initial-fetch.js
  package.json
  pages/_app.js
  pages/admin/index.js
  pages/api/proxy.js
  yarn.lock
Labels: feature

#982 Improve text clarity of Add and Copy timetable buttons
  lib/components/modification/timetables.js
Labels: feature

#978 Add region creation message
  lib/components/create-region.js
  package.json
Labels: bug

#979 Fix issue causing half the map not to show
  lib/components/map/index.js
Labels: bug

#980 Fix selected project in Analysis screen
  lib/components/sidebar.js
  pages/_app.js
Labels: bug

#976 Use built in CSS import
  package.json
  pages/_app.js
  pages/_document.js
  public/static/react-datetime.css
  styles.css
  yarn.lock
Labels: optimization

#960 Documentation review
  docs/analysis/configuration.md
  docs/analysis/index.md
  docs/analysis/methodology.md
  docs/analysis/regional.md
  docs/edit-scenario/example.md
  docs/edit-scenario/export.md
  docs/edit-scenario/index.md
  docs/edit-scenario/modifications.md
  docs/edit-scenario/phasing.md
  docs/edit-scenario/timetable.md
  docs/edit-scenario/usage.md
  docs/glossary.md
  docs/index.rst
  docs/learn-more/faq.md
  docs/prepare-inputs/index.md
  docs/prepare-inputs/upload-opportunity-data.md
  docs/static/img/alignment-options.png
  docs/static/img/make-control-point.png
  docs/static/img/remove-trips.png
  docs/static/img/scenario-chooser.png
  docs/static/img/stop-edit-legend.png
Labels: WIP

#981 Allow changing selected phase from timetable without crashing
  lib/components/modification/__tests__/__snapshots__/add-trip-pattern.js.snap
  lib/components/modification/__tests__/__snapshots__/frequency-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable-entry.js.snap
  lib/components/modification/__tests__/__snapshots__/timetable.js.snap
  lib/components/modification/__tests__/timetable-entry.js
  lib/components/modification/__tests__/timetable.js
  lib/components/modification/add-trip-pattern.js
  lib/components/modification/convert-to-frequency.js
  lib/components/modification/frequency-entry.js
  lib/components/modification/phase.js
  lib/components/modification/timetable-entry.js
  lib/components/modification/timetable.js
  lib/components/modification/timetables.js
  lib/containers/add-trip-pattern.js
  lib/containers/convert-to-frequency.js
  lib/selectors/all-phase-from-timetable-stops.js
Labels: bug

#994 Include reroute in modification bounds
  lib/selectors/modification-bounds.js
  lib/with-initial-fetch.js
Labels: bug

#997 Clear warnings and errors on page load
  pages/regions/[regionId]/analysis.js
Labels: bug

#995 Update region after saving to ensure latest nonce is used
  lib/components/edit-region.js
Labels: bug

#962 Setup Cypress and Github Actions for adding new tests later
  .github/workflows/nodejs.yml
  cypress.json
  cypress/.gitignore
  cypress/fixtures/profile.json
  cypress/fixtures/regions.json
  cypress/fixtures/regions/download.sh
  cypress/fixtures/regions/portland/.gitignore
  cypress/fixtures/regions/portland/overpass-query.txt
  cypress/integration/region_spec.js
  cypress/screenshots/.gitignore
  cypress/support/commands.js
  cypress/support/index.js
  cypress/videos/.gitignore
  lib/components/map/index.js
  lib/components/map/mapbox-gl.js
  lib/components/modification/__tests__/timetable.js
  lib/components/sidebar.js
  next.config.js
  package.json
  yarn.lock
Labels: optimization

#998 Remove clear bundle button
  lib/components/modification/editor.js
  lib/containers/__tests__/__snapshots__/modification-editor.js.snap
  yarn.lock
Labels: bug

#999 Use `get` for finding the feed id
  lib/components/modification/list.js
Labels: bug

#1001 Prevent overscroll in full screen mode
  lib/selectors/modification-bounds.js
  pages/_app.js
  styles.css
Labels: bug
