Repository conveyal/analysis-ui, pull requests merged in 2020-09, with the labels that each got.

#1199 Fetch regions from JavaScript API
  .eslintrc.json
  .github/workflows/lint-jest-build.yml
  cypress.json
  cypress/integration/0-regions.js
  cypress/integration/2-opportunities.js
  cypress/integration/3-projects.js
  cypress/integration/4-scenarios.js
  cypress/integration/5-modifications.js
  cypress/integration/6-analysis.js
  cypress/support/commands.js
  db/connect.js
  lib/actions/__tests__/region.js
  lib/actions/region.js
  lib/auth0.ts
  lib/components/__tests__/__snapshots__/create-region.js.snap
  lib/components/__tests__/__snapshots__/edit-region.js.snap
  lib/components/__tests__/__snapshots__/select-region.js.snap
  lib/components/__tests__/create-region.js
  lib/components/__tests__/edit-region.js
  lib/components/__tests__/select-region.js
  lib/components/edit-region.js
  lib/components/full-spinner.tsx
  lib/components/logo.js
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/select-region.tsx
  lib/db/authenticated-collection.ts
  lib/db/connect.ts
  lib/hooks/use-controlled-input.ts
  lib/hooks/use-region.ts
  lib/hooks/use-regions.ts
  lib/hooks/use-route-to.ts
  lib/hooks/use-user.ts
  lib/layouts/map.js
  lib/logrocket.js
  lib/user.js
  lib/user.ts
  lib/utils/modification.js
  lib/utils/safe-fetch.ts
  lib/with-auth.tsx
  lib/with-initial-fetch.tsx
  package.json
  pages/_app.tsx
  pages/api/callback.ts
  pages/api/login.ts
  pages/api/logout.ts
  pages/api/profile.ts
  pages/api/regions/[regionId].ts
  pages/api/regions/index.ts
  pages/api/session.ts
  pages/index.js
  pages/index.tsx
  pages/regions/[regionId]/edit.js
  pages/regions/[regionId]/edit.tsx
  pages/regions/create.js
  pages/regions/create.tsx
  pages/regions/index.js
  yarn.lock
Labels: automerge, feature

#1218 Convert new APIs to handle all collection types
  lib/actions/region.js
  lib/db/authenticated-collection.ts
  lib/db/utils.ts
  lib/hooks/use-collection.ts
  lib/hooks/use-model.ts
  lib/hooks/use-region.ts
  lib/hooks/use-regions.ts
  lib/reducers/__tests__/__snapshots__/region.js.snap
  lib/reducers/__tests__/region.js
  lib/reducers/region.js
  pages/api/db/[collection]/[_id].ts
  pages/api/db/[collection]/index.ts
  pages/api/regions/[regionId].ts
  pages/index.tsx
  pages/regions/[regionId]/edit.tsx
  pages/regions/create.tsx
  pages/regions/index.tsx
  yarn.lock
Labels: automerge, feature

#1210 Enable worker-side accessibility calculation by specifying opportunities
  lib/actions/analysis/index.js
  lib/actions/analysis/parse-times-data.ts
  lib/modules/opportunity-datasets/selectors.js
  lib/selectors/accessibility.js
  lib/selectors/percentile-curves.js
Labels: automerge, feature

#1235 Disable recording to speed up cypress tests
  .github/workflows/lint-jest-build.yml
  cypress.json
  cypress/integration/0-regions.js
  cypress/support/index.js
  package.json
  yarn.lock
Labels: automerge, optimization

#1244 Disable close on overlay for regional analysis creation
  lib/components/analysis/create-regional.tsx
Labels: automerge, bug

#1246 Try CodeQL
  .github/workflows/codeql-analysis.yml
  lib/components/analysis/profile-request-display.tsx
Labels: automerge, experimental, feature

#1243 Fix bug causing new modifications to not show on map
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/list.tsx
  lib/components/modifications-map/display-all.tsx
  pages/regions/[regionId]/projects/[projectId]/index.tsx
  pages/regions/[regionId]/projects/[projectId]/modifications/index.tsx
Labels: automerge, bug

#1227 Presets (previously known as Bookmarks)
  cypress/integration/6-analysis.js
  lib/actions/analysis/parse-times-data.ts
  lib/actions/bookmark.ts
  lib/auth0.ts
  lib/components/__tests__/__snapshots__/project-title.js.snap
  lib/components/__tests__/__snapshots__/select-project.js.snap
  lib/components/analysis/__tests__/__snapshots__/bookmark-chooser.js.snap
  lib/components/analysis/__tests__/__snapshots__/profile-request-display.js.snap
  lib/components/analysis/__tests__/__snapshots__/regional-results.js.snap
  lib/components/analysis/__tests__/bookmark-chooser.js
  lib/components/analysis/bookmark-chooser.tsx
  lib/components/analysis/egress-mode-selector.js
  lib/components/analysis/index.tsx
  lib/components/analysis/profile-request-display.tsx
  lib/components/analysis/single-point-settings.tsx
  lib/components/error-modal.tsx
  lib/components/export-project.tsx
  lib/components/icon-button.tsx
  lib/components/modification/__tests__/__snapshots__/copy-timetable.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  lib/components/modification/__tests__/__snapshots__/reroute.js.snap
  lib/components/modification/copy-timetable.tsx
  lib/components/modification/create.tsx
  lib/components/presets.tsx
  lib/db/authenticated-collection.ts
  lib/db/with-collection.ts
  lib/hooks/use-collection.ts
  lib/hooks/use-model.ts
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/heading.js.snap
  lib/modules/opportunity-datasets/components/heading.js
  lib/reducers/__tests__/__snapshots__/region.js.snap
  lib/reducers/region.js
  lib/selectors/bookmark-data.js
  lib/selectors/bookmarks.js
  lib/user.ts
  lib/utils/api.ts
  lib/utils/create-grid.ts
  lib/utils/mock-data.js
  lib/utils/safe-fetch.ts
  migrations/1599703681398-bookmarks-to-presets.js
  package.json
  pages/_app.tsx
  pages/api/callback.ts
  pages/api/db/[collection]/[_id].ts
  pages/api/db/[collection]/index.ts
  pages/api/login.ts
  pages/api/logout.ts
  pages/api/profile.ts
  pages/api/session.ts
  pages/index.tsx
  pages/regions/[regionId]/analysis.tsx
  pages/regions/[regionId]/opportunities/index.js
  pages/regions/[regionId]/regional/index.js
  pages/regions/[regionId]/resources/[resourceId].js
  yarn.lock
Labels: automerge, cleanup, feature

#1245 Remove React-GA dependency
  lib/gtag.ts
  package.json
  pages/_app.tsx
  pages/_document.tsx
  yarn.lock
Labels: automerge, cleanup

#1247 Prevent CKMeans throwing an error from lack of data
  lib/components/map/gridualizer.js
  lib/components/map/gridualizer.tsx
  lib/modules/opportunity-datasets/components/dotmap.tsx
  lib/selectors/regional-display-scale.ts
Labels: automerge, bug

#1248 Convert all /utils files to TypeScript
  lib/components/modifications-map/transit-editor/__tests__/index.js
  lib/utils/__tests__/__snapshots__/jsolines.ts.snap
  lib/utils/__tests__/__snapshots__/modification.ts.snap
  lib/utils/__tests__/aggregate-accessibility.ts
  lib/utils/__tests__/bounds.ts
  lib/utils/__tests__/get-hop-times.ts
  lib/utils/__tests__/get-line-string.ts
  lib/utils/__tests__/get-route-polyline.ts
  lib/utils/__tests__/get-stop-near-point.ts
  lib/utils/__tests__/get-stops.ts
  lib/utils/__tests__/jsolines.ts
  lib/utils/__tests__/modification.ts
  lib/utils/__tests__/reproject-coordinates.ts
  lib/utils/__tests__/timetable.ts
  lib/utils/__tests__/update-add-stops-terminus.ts
  lib/utils/aggregate-accessibility.ts
  lib/utils/bounds.ts
  lib/utils/clean-project-scenario-name.ts
  lib/utils/component.tsx
  lib/utils/create-draw-tile.ts
  lib/utils/download-data.ts
  lib/utils/download-geotiff.ts
  lib/utils/download-json.ts
  lib/utils/export-project.ts
  lib/utils/frequency-entry.ts
  lib/utils/get-existing-stops-along-pattern.ts
  lib/utils/get-hop-times.ts
  lib/utils/get-line-string.ts
  lib/utils/get-route-polyline.ts
  lib/utils/get-stop-near-point.ts
  lib/utils/get-stop-radius.ts
  lib/utils/get-stops.ts
  lib/utils/get.ts
  lib/utils/grid-cell-interpolator.ts
  lib/utils/hex-color-contrast.ts
  lib/utils/jsolines.ts
  lib/utils/log-dom-event.ts
  lib/utils/log-error.ts
  lib/utils/mapbox-search.ts
  lib/utils/markers.ts
  lib/utils/math.ts
  lib/utils/metric.ts
  lib/utils/mock-data.tsx
  lib/utils/modification.ts
  lib/utils/multi.ts
  lib/utils/nearest-interpolator.ts
  lib/utils/patterns.ts
  lib/utils/predict-job-time-remaining.ts
  lib/utils/reproject-coordinates.ts
  lib/utils/rgb-color-contrast.ts
  lib/utils/set-search-parameter.ts
  lib/utils/time.ts
  lib/utils/timeout.ts
  lib/utils/timetable.ts
  lib/utils/update-add-stops-terminus.ts
  package.json
  yarn.lock
Labels: automerge, cleanup

#1250 Ensure cleared projects show results as stale
  lib/components/map/geojson.tsx
  lib/components/map/isochrones.tsx
  lib/selectors/__tests__/__snapshots__/isochrone.js.snap
  lib/selectors/comparison-isochrone.ts
  lib/selectors/isochrone.ts
  lib/selectors/profile-request-has-changed.ts
  lib/utils/__tests__/__snapshots__/jsolines.ts.snap
  lib/utils/jsolines.ts
Labels: automerge, bug
