Repository conveyal/analysis-ui, pull requests merged in 2021-02, with the labels that each got.

#1450 OD upload status
  cypress/integration/2-opportunities.ts
  cypress/support/opportunities.ts
  i18n/en.json
Labels: automerge

#1454 Upgrade to react v17 to utilize latest nextjs features
  jest/enzyme.js
  lib/components/__tests__/__snapshots__/collapsible.js.snap
  lib/components/analysis/__tests__/__snapshots__/scenario-application-error.js.snap
  lib/components/modification/__tests__/__snapshots__/list.js.snap
  package.json
  yarn.lock
Labels: dependencies

#1458 Select origin point set
  .github/workflows/lint-jest-build.yml
  cypress/support/analysis.ts
  lib/actions/analysis/regional.ts
  lib/components/analysis/create-regional.tsx
  lib/components/docs-link.tsx
  lib/modules/opportunity-datasets/components/__tests__/__snapshots__/upload.js.snap
  lib/utils/auth-fetch.ts
  lib/utils/calculate-grid-points.ts
  lib/utils/safe-fetch.ts
  pages/regions/[regionId]/edit.tsx
Labels: feature

#1474 Show falsy values in profile request display
  lib/components/analysis/profile-request-display.tsx
Labels: bug

#1480 Limit transfers to 1 character (single digit)
  lib/components/analysis/__tests__/__snapshots__/profile-request-editor.js.snap
  lib/components/analysis/profile-request-editor.tsx
Labels: bug

#1485 Cache Cypress binary, skip initial installation
  .github/workflows/lint-jest-build.yml
Labels: bug

#1484 Return updated document in db PUTs
  cypress/integration/6-analysis.ts
  lib/components/presets.tsx
  lib/db/authenticated-collection.ts
  lib/hooks/use-collection.ts
Labels: bug
